services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    working_dir: /var/www/html
    volumes:
      - /Users/myboy/social-network/backend:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.4
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "13306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "18080:80"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    volumes:
      - /Users/myboy/social-network/backend:/var/www/html
      - /Users/myboy/social-network/backend/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "18888:80"
    depends_on:
      - php

volumes:
  db_data:
